2024-03-21 15:31:08,166 INFO    Thread-8 (_run_job):22292 [wandb_setup.py:_flush():76] Current SDK version is 0.16.4
2024-03-21 15:31:08,167 INFO    Thread-8 (_run_job):22292 [wandb_setup.py:_flush():76] Configure stats pid to 22292
2024-03-21 15:31:08,167 INFO    Thread-8 (_run_job):22292 [wandb_setup.py:_flush():76] Loading settings from C:\Users\games\.config\wandb\settings
2024-03-21 15:31:08,167 INFO    Thread-8 (_run_job):22292 [wandb_setup.py:_flush():76] Loading settings from D:\programowanie\python\projekt zespo³owy\struktura\architectures\ml\RandomForest\wandb\settings
2024-03-21 15:31:08,167 INFO    Thread-8 (_run_job):22292 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'forest_test_1', 'entity': 'czarna-magia', 'root_dir': 'D:\\programowanie\\python\\projekt zespo³owy\\struktura\\architectures\\ml\\RandomForest', 'sweep_id': '2oe4hlvc', 'run_id': '0vhbup4q', 'sweep_param_path': 'D:\\programowanie\\python\\projekt zespo³owy\\struktura\\architectures\\ml\\RandomForest\\wandb\\sweep-2oe4hlvc\\config-0vhbup4q.yaml'}
2024-03-21 15:31:08,167 INFO    Thread-8 (_run_job):22292 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-21 15:31:08,167 INFO    Thread-8 (_run_job):22292 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'train_RandomForest.py', 'program_abspath': 'D:\\programowanie\\python\\projekt zespo³owy\\struktura\\architectures\\ml\\RandomForest\\train_RandomForest.py', 'program': 'D:\\programowanie\\python\\projekt zespo³owy\\struktura\\architectures\\ml\\RandomForest\\train_RandomForest.py'}
2024-03-21 15:31:08,167 INFO    Thread-8 (_run_job):22292 [wandb_init.py:_log_setup():526] Logging user logs to D:\programowanie\python\projekt zespo³owy\struktura\architectures\ml\RandomForest\wandb\run-20240321_153108-0vhbup4q\logs\debug.log
2024-03-21 15:31:08,168 INFO    Thread-8 (_run_job):22292 [wandb_init.py:_log_setup():527] Logging internal logs to D:\programowanie\python\projekt zespo³owy\struktura\architectures\ml\RandomForest\wandb\run-20240321_153108-0vhbup4q\logs\debug-internal.log
2024-03-21 15:31:08,168 INFO    Thread-8 (_run_job):22292 [wandb_init.py:init():566] calling init triggers
2024-03-21 15:31:08,168 INFO    Thread-8 (_run_job):22292 [wandb_init.py:init():573] wandb.init called with sweep_config: {'max_depth': 14, 'n_estimators': 12, 'sample_rate': 0.1, 'test_size': 0.3}
config: {}
2024-03-21 15:31:08,168 INFO    Thread-8 (_run_job):22292 [wandb_init.py:init():611] wandb.init() called when a run is still active
2024-03-21 15:31:08,623 ERROR   Thread-8 (_run_job):22292 [wandb_init.py:init():1204] error
Traceback (most recent call last):
  File "D:\programowanie\python\projekt zespo³owy\struktura\.venv\Lib\site-packages\wandb\sdk\wandb_init.py", line 1176, in init
    run = wi.init()
          ^^^^^^^^^
  File "D:\programowanie\python\projekt zespo³owy\struktura\.venv\Lib\site-packages\wandb\sdk\wandb_init.py", line 612, in init
    with telemetry.context() as tel:
  File "D:\programowanie\python\projekt zespo³owy\struktura\.venv\Lib\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "D:\programowanie\python\projekt zespo³owy\struktura\.venv\Lib\site-packages\wandb\sdk\wandb_run.py", line 759, in _telemetry_callback
    self._telemetry_flush()
  File "D:\programowanie\python\projekt zespo³owy\struktura\.venv\Lib\site-packages\wandb\sdk\wandb_run.py", line 770, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "D:\programowanie\python\projekt zespo³owy\struktura\.venv\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 101, in _publish_telemetry
    self._publish(rec)
  File "D:\programowanie\python\projekt zespo³owy\struktura\.venv\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 51, in _publish
    self._sock_client.send_record_publish(record)
  File "D:\programowanie\python\projekt zespo³owy\struktura\.venv\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 221, in send_record_publish
    self.send_server_request(server_req)
  File "D:\programowanie\python\projekt zespo³owy\struktura\.venv\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "D:\programowanie\python\projekt zespo³owy\struktura\.venv\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "D:\programowanie\python\projekt zespo³owy\struktura\.venv\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] Nawi¹zane po³¹czenie zosta³o przerwane przez oprogramowanie zainstalowane w komputerze-hoœcie
