Traceback (most recent call last):
  File "D:\programowanie\python\projekt zespo≈Çowy\oko_neptuna\architectures\ml\RandomForest\train.py", line 64, in train
    clf = model(**config)
          ^^^^^^^^^^^^^^^
TypeError: 'RandomForestClassifier' object is not callable